### ISSUE TITLE
Parameters to specify in reference_project.json for a smooth run of the *.js in the Webplotdigitizer repository. 

### ISSUE THREAD

**Issue by rodricfanou** [ankitrohatgi/WebPlotDigitizer#185]
Hi Ankit, 

I uploaded the reference_project.json and the image I used for testing the batch_process.js. 
[test_files.zip](https://github.com/ankitrohatgi/WebPlotDigitizer/files/3826561/test_files.zip)

As you suggested, the reference_project.json contains a modified version of the output when getting the data through the web tool and thus all the calibres needed to serialise the image. 
However, while running the batch_process.js, we always bumped in this error: 

[ { _dim: undefined,
    _dataPoints:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    _connections: [],
    _selections: [],
    _hasMetadata: true,
    _mkeys: [ 'Label' ],
    name: 'Default Dataset',
    variableNames: [ 'x', 'y' ] } ]
TypeError: Cannot read property '_delX' of undefined
    at appendData (/.../WebPlotDigitizer/app/node-module/wpd-4.2/wpd_node.js:2844:67)
    at wpd.BarExtractionAlgo.run (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/app/node-module/wpd-4.2/wpd_node.js:2884:21)
    at digitizeImage (/.../WebPlotDigitizer/node_examples/batch_process.js:40:32)
    at jimp.read.then.img (/.../WebPlotDigitizer/node_examples/batch_process.js:74:69)
TypeError: Cannot read property '_delX' of undefined
    at appendData (/.../WebPlotDigitizer/app/node-module/wpd-4.2/wpd_node.js:2844:67)
    at wpd.BarExtractionAlgo.run (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/app/node-module/wpd-4.2/wpd_node.js:2884:21)
    at digitizeImage (/.../WebPlotDigitizer/node_examples/batch_process.js:40:32)
    at jimp.read.then.img (/.../WebPlotDigitizer/node_examples/batch_process.js:74:69)

No keys of the reference_project.json is entitled "dim". As a result dim is undefined and I think that's why we encounter the error "Cannot read property '_delX' of undefined". Is there any way you can transmit us:

1- a working version of the reference_project.json for the type of mirth graph attached? or
2- a template of a working reference_project.json? or 
3- a pointer to all the calibre the file reference_project.json should contain for the tool to function properly with nodejs? 

Thanks in advance.

**Comment by mbruyere** [comment]
Hi all,

I am having the same issue.

[ { _dim: undefined,
    _dataPoints: [],
    _connections: [],
    _selections: [],
    _hasMetadata: false,
    _mkeys: [ 'Label' ],
    name: 'Default Dataset',
    variableNames: [ 'x', 'y' ] } ]
Line 29

TypeError: Cannot read property '_delX' of undefined
    at appendData (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/app/node-module/wpd-4.2/wpd_node.js:2844:67)
    at wpd.BarExtractionAlgo.run (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/app/node-module/wpd-4.2/wpd_node.js:2884:21)
    at digitizeImage (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/node_examples/batch_process.js:42:32)
    at jimp.read.then.img (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/node_examples/batch_process.js:76:69)
TypeError: Cannot read property '_delX' of undefined
    at appendData (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/app/node-module/wpd-4.2/wpd_node.js:2844:67)
    at wpd.BarExtractionAlgo.run (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/app/node-module/wpd-4.2/wpd_node.js:2884:21)
    at digitizeImage (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/node_examples/batch_process.js:42:32)
    at jimp.read.then.img (/Users/Roderick/Desktop/Projects/WebPlotDigitizer/node_examples/batch_process.js:76:69)


This is a minimum file config 
serialize() {
        return this._wasRun ? {
                algoType: "AveragingWindowWithStepSizeAlgo",
                xmin: this._xmin,
                delx: this._delx,
                xmax: this._xmax,
                ymin: this._ymin,
                ymax: this._ymax,
                lineWidth: this._lineWidth
            } :
            null;

Will like to get some guidance 
Thx
